name: techapp
description: made by technobyte

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_svg: ^1.0.0
  firebase_core: ^1.10.5
  firebase_messaging: ^11.2.4
  firebase_auth: ^3.3.3
  google_sign_in: ^5.2.1
  flutter_lints: ^1.0.0
  curved_navigation_bar: ^1.0.1
  card_swiper : ^1.0.4
  http: ^0.13.4
  url_launcher: ^6.0.17
  animated_splash_screen: ^1.1.0
  flutter_local_notifications: ^9.1.5
  localstorage: ^4.0.0+1
  dialogflow_flutter: ^0.0.3
  auto_size_text: ^3.0.0
  progress_indicator_button: ^0.0.3
  loading_animation_widget:
  retrofit: ^3.0.1
  dio: ^4.0.4
  built_value: ^8.1.3
  flutter_launcher_icons: ^0.9.2
  avatar_glow: ^2.0.2
  font_awesome_flutter: ^9.0.0
  shimmer: ^2.0.0
  particles_flutter: ^0.1.1

flutter_icons:
  image_path_android: "assets/images/icon.png"
  image_path_ios: "assets/images/icon.png"
  android: true 
  ios: true 
  adaptive_icon_background: "assets/images/icon.png" 
  adaptive_icon_foreground: "assets/images/icon.png" 


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^3.0.1+1
  build_runner: ^2.1.7
  built_value_generator: ^8.1.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/icons/
  
  fonts:
   - family: OpenSans SemiBold
     fonts:
     - asset: assets/fonts/OpenSans-SemiBold.ttf
   - family: Poppins
     fonts:
     - asset: assets/fonts/Poppins-Black.ttf
   - family: glitch
     fonts:
     - asset: assets/fonts/glitch.otf